services:
  db:
    container_name: db
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c "listen_addresses=*"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 5400:5432
    networks:
      - dibo-network

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:2025-05-27-1
    restart: unless-stopped
    ports:
      - "5040:5050"
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker-scripts/pg-admin/servers.json:/pgadmin4/servers.json
    networks:
      - dibo-network

  easy-generator-backend:
    container_name: easy-generator-backend
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.apps
      args:
        - APP_NAME=easy-generator-backend
    env_file:
      - apps/easy-generator-backend/.env
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - dibo-network

  easy-generator-ui:
    container_name: easy-generator-ui
    depends_on:
      - easy-generator-backend
    build:
      context: .
      dockerfile: Dockerfile.apps
      args:
        - APP_NAME=easy-generator-ui
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - dibo-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  dibo-network:
    driver: bridge
